version: "3.7"
services:
#  db:
#    build: "./db"
#    image: db-ecommerceget-image
##    restart: always
#    container_name: db-ecommerceget-container
#    env_file:
#      - ./db/db.env
#    networks:
#      - ecommerceget-network
#    volumes:
#      - ./db/data:/var/lib/postgresql/data
#    ports:
#      - "${PORT_DB_DOCKER}:5432"
  app:
    build:
      context: "./"
    env_file:
      - ./prod.env
    working_dir: /usr/src/ecommerceget
    image: api-ecommerceget-image
    container_name: api-ecommerceget-container
    restart: on-failure
    ports:
      - "${PORT_SERVER_DOCKER}:8080"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - ecommerceget-network
networks:
  ecommerceget-network: